version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    exclude-paths:
      - ".github/workflows/release.yml"
      - ".github/workflows/release.yaml"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
