pub fn install_forge_step() -> &'static str {
    "      - name: Install forge\n        run: cargo install --git https://github.com/pesap/forge --locked forge\n"
}

pub fn setup_uv_step() -> &'static str {
    "      - uses: astral-sh/setup-uv@v6\n        with:\n          enable-cache: true\n          cache-dependency-glob: |\n            pyproject.toml\n            uv.lock\n"
}

pub fn uv_sync_locked_step() -> &'static str {
    "      - run: uv sync --all-groups --locked\n"
}

pub fn uv_lock_check_step() -> &'static str {
    "      - run: uv lock --check\n"
}

pub fn uv_run_locked_step(command: &str) -> String {
    format!("      - run: uv run --locked {command}\n")
}

pub fn read_only_checkout_step() -> &'static str {
    "      - uses: actions/checkout@v6\n        with:\n          persist-credentials: false\n"
}

pub fn forge_update_check_step() -> &'static str {
    "      - run: forge update --path . --check\n"
}

pub fn read_only_permissions() -> &'static str {
    "permissions:\n  contents: read\n\n"
}

pub fn cancel_redundant_ci_concurrency() -> &'static str {
    "concurrency:\n  group: ${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: true\n\n"
}

pub fn serialized_update_concurrency() -> &'static str {
    "concurrency:\n  group: ${{ github.workflow }}\n  cancel-in-progress: false\n\n"
}

pub fn serialized_ref_concurrency() -> &'static str {
    "concurrency:\n  group: ${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: false\n\n"
}

pub fn serialized_release_concurrency() -> &'static str {
    "concurrency:\n  group: ${{ github.workflow }}-${{ github.event.release.id }}\n  cancel-in-progress: false\n\n"
}

pub fn job_timeout() -> &'static str {
    "    timeout-minutes: 20\n"
}

pub fn render_forge_update_workflow() -> String {
    format!(
        "name: forge-update\n\non:\n  schedule:\n    - cron: \"0 8 * * 1\"\n  workflow_dispatch:\n\n{}permissions:\n  contents: write\n  pull-requests: write\n\njobs:\n  update:\n    runs-on: ubuntu-latest\n{}    steps:\n{}      - name: Install Rust\n        uses: dtolnay/rust-toolchain@stable\n{}{}      - name: Update Forge-managed infrastructure\n        run: forge update --path .\n      - name: Refresh dependency lockfile\n        run: uv lock\n      - name: Create pull request\n        uses: peter-evans/create-pull-request@v8\n        with:\n          commit-message: \"chore: update Forge-managed infrastructure\"\n          branch: chore/forge-update\n          title: \"chore: update Forge-managed infrastructure\"\n          body: |\n            This PR was automatically generated by the forge update workflow.\n\n            - Runs `forge update --path .`\n            - Runs `uv lock` so generated locked CI stays in sync\n            - Updates only Forge-managed infra files and dependency lockfiles\n",
        serialized_update_concurrency(),
        job_timeout(),
        read_only_checkout_step(),
        setup_uv_step(),
        install_forge_step()
    )
}

#[cfg(test)]
mod tests {
    use crate::blueprint::github_actions::{
        cancel_redundant_ci_concurrency, forge_update_check_step, install_forge_step, job_timeout,
        read_only_checkout_step, read_only_permissions, render_forge_update_workflow,
        serialized_ref_concurrency, serialized_release_concurrency, serialized_update_concurrency,
        setup_uv_step, uv_lock_check_step, uv_run_locked_step, uv_sync_locked_step,
    };

    #[test]
    fn forge_ci_steps_install_and_check_managed_infrastructure() {
        assert!(install_forge_step().contains("cargo install --git"));
        assert!(install_forge_step().contains("--locked forge"));
        assert_eq!(
            forge_update_check_step(),
            "      - run: forge update --path . --check\n"
        );
        assert_eq!(
            read_only_permissions(),
            "permissions:\n  contents: read\n\n"
        );
        assert_eq!(
            cancel_redundant_ci_concurrency(),
            "concurrency:\n  group: ${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: true\n\n"
        );
        assert_eq!(
            serialized_update_concurrency(),
            "concurrency:\n  group: ${{ github.workflow }}\n  cancel-in-progress: false\n\n"
        );
        assert_eq!(
            serialized_ref_concurrency(),
            "concurrency:\n  group: ${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: false\n\n"
        );
        assert_eq!(
            serialized_release_concurrency(),
            "concurrency:\n  group: ${{ github.workflow }}-${{ github.event.release.id }}\n  cancel-in-progress: false\n\n"
        );
        assert_eq!(job_timeout(), "    timeout-minutes: 20\n");
        assert!(setup_uv_step().contains("astral-sh/setup-uv@v6"));
        assert!(setup_uv_step().contains("enable-cache: true"));
        assert!(setup_uv_step().contains("uv.lock"));
        assert_eq!(
            uv_sync_locked_step(),
            "      - run: uv sync --all-groups --locked\n"
        );
        assert_eq!(uv_lock_check_step(), "      - run: uv lock --check\n");
        assert_eq!(
            uv_run_locked_step("prek run --all-files"),
            "      - run: uv run --locked prek run --all-files\n"
        );
        assert!(read_only_checkout_step().contains("actions/checkout@v6"));
        assert!(read_only_checkout_step().contains("persist-credentials: false"));
    }

    #[test]
    fn forge_update_workflow_serializes_runs_without_canceling_in_progress_updates() {
        let workflow = render_forge_update_workflow();

        assert!(workflow.contains(serialized_update_concurrency()));
        assert!(workflow.contains("  cancel-in-progress: false\n\npermissions:"));
    }

    #[test]
    fn forge_update_workflow_runs_update_and_opens_pull_request() {
        let workflow = render_forge_update_workflow();

        assert!(workflow.contains("name: forge-update"));
        assert!(workflow.contains(install_forge_step()));
        assert!(workflow.contains("run: forge update --path ."));
        assert!(workflow.contains("run: uv lock"));
        assert!(workflow.contains("actions/checkout@v6"));
        assert!(workflow.contains("persist-credentials: false"));
        assert!(workflow.contains("peter-evans/create-pull-request@v8"));
        assert!(workflow.contains("pull-requests: write"));
        assert!(workflow.contains(job_timeout()));
        assert!(workflow.contains("Forge-managed infrastructure"));
        assert!(!workflow.contains("template-managed"));
    }
}
