name: release-please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    name: release please
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to create release PRs and tags
      pull-requests: write # required to open/update release PRs
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          release-type: rust
          package-name: forge
